### ISSUE TITLE
Spindle DIR as Enable Acting differently in V1.1e

### ISSUE THREAD

**Issue by bvernham** [gnea/grbl#71]
I am using the option #define USE_SPINDLE_DIR_AS_ENABLE_PIN to "wake up" my spindle controller.

When this pin goes high (M3) I use it to turn on the power supply (48V DC) and in anticipation of the speed request (S####).

With V1.1e, when issue the M3, nothing happens until I issue the S####.

Can this be changes so that the M3 will set the DIR pin high so my spindle controller can turn on the power supply as with V0.9J?

Thanks

Bruce

**Comment by chamnit** [comment]
@bvernham : Thanks. I'll take a look at it when I get a chance. This feature was one of the things I overlooked to test.

**Comment by fl0yd** [comment]
@chamnit is it as simple as making the rpm have a default value of 0.0?

```
// Sets spindle running state with direction, enable, and spindle PWM.
  void spindle_set_state(uint8_t state, float rpm);
```

Changes to

```
// Sets spindle running state with direction, enable, and spindle PWM.
  void spindle_set_state(uint8_t state, float rpm = 0.0);
```

**Comment by chamnit** [comment]
@fl0yd : Nope. But I just pushed a fix. I'll make a release whenever someone reports back that it works. Please make sure to test for the USE_SPINDLE_DIR_AS_ENABLE_PIN option turned off too. If you have a laser, also test with this. Thanks.

**Comment by fl0yd** [comment]
Thanks @chamnit we'll have to see what @bvernham's test show.

I was looking at the commit and still don't see how passing in a null value for `rpm` will set the pin high on strictly an `M4` without an `SXXXX` value.  Though my familiarity with the code started today... :)

**Comment by chamnit** [comment]
@fl0yd : Look at the source code file, not the commit. It'll make more sense there.

**Comment by bvernham** [comment]
Gentlemen, the difference is with reaction to the M3 command with or without and SXXXX value < the minimum configured value. Thanks Bruce

---------- Original Message ----------

**Comment by chamnit** [comment]
This is what I fixed in the last push. Please test. Thanks.

**Comment by chamnit** [comment]
@bvernham : Were you able to test this fix?

**Comment by bvernham** [comment]
Not yet. I went back to 0.9J because 1.1e does not work with inventables easel.

---------- Original Message ----------

**Comment by chamnit** [comment]
@bvernham : FWIW, I met with Inventables and some of their Easel devs over the holiday break. They were quite busy with other higher priority tasks, but they are still planning to update to v1.1's new protocol AFAIK. I notified them back in October to get it into their queue.

**Comment by chamnit** [comment]
@bvernham : I am assuming that this is fixed unless you report otherwise. Closing.
